## YAML Template.
---

server:
  port: 5555

  #Setting logging levels
logging:
    level:
      com.netflix: WARN
      org.springframework.web: WARN
      com.notix: DEBUG

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/
        
        
zuul.sensitiveHeaders: Cookie,Set-Cookie
##zuul:
  ##  prefix: /api
    ##routes:
      ##  helloworld: /hello/**
        ##demomodule: /test/**
        ##authserver: /authsrvrgateway/**
        ##authclient: /authclientgateway/**